---
title: "Introduction to renv"
author: "Kevin Ushey"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment  = "#>",
  eval     = FALSE
)
```

The `renv` package is a new effort to bring private project-local R libraries
to your projects. The goal is for `renv` to be a robust, stable replacement for
the [Packrat](https://rstudio.github.io/packrat/) package, with fewer surprises
and better default behaviors.

`renv` works by writing some project-specific infrastructure to the project.
In particular, an `.Rprofile` is written to the project root, and this file
is sourced by R when new R sessions are started in the project directory.
The startup machinery then ensures that all relevant state (R repositories,
library paths, et al.) is set as required.

Underlying the philosophy of `renv` is that any existing workflows should
just work as they did before -- `renv` helps manage library paths (and other
project-specific state) to help share and isolate project dependencies, and
the existing tools you've used for managing R packages should work as before.

## Workflow

The general workflow when working with `renv` is as thus:

1. Call `renv::init()` to initialize a new project-local environment, with a
   private R library;

2. Work in the project as normal, installing and removing new R packages as
   they are needed in the project,

3. Call `renv::snapshot()` to save the state of the project library to the
   lockfile (called `renv.lock`),

4. Call `renv::restore()` to restore the state of the project library, based
   on the state of the lockfile previously generated by `renv::snapshot()`.

The `renv::init()` function attempts to ensure the newly-created project
library includes all R packages currently used by the project. It does this
by crawling any R files within the project for dependencies with the
`renv::dependencies()` function, which records any discovered R packages
used in the project, and the file from which that package was used / declared.

## Reproducibility

With Packrat, one can save and restore the state of the private library with
`packrat::snapshot()` and `packrat::restore()`. The same model is used here:

- Call `renv::snapshot()` to save the state of your project to a lockfile; and
  
- Call `renv::restore()` to restore the state of your project from a lockfile.

Be aware that `renv::restore()` may fail if a package was originally installed
through a CRAN-available binary, but that binary is no longer available. `renv`
will attempt to install the package from sources in this situation, but attempts
to install from source can (and often do) fail due to missing system
prerequisites for compilation of a package.

By default, `renv` will maintain and use a global cache of packages during
`renv::restore()`, so (at least on the same machine) if that cache is maintained
old projects will be restored by copying or linking from an installation
discovered in the cache.

## Comparison with Packrat

`renv` differs from Packrat in the following ways:

1. `renv` no longer attempts to explicitly download and track R package sources
   within your project. This was a frustrating default that operated under the
   assumption that you might later want to be able to restore a project's private
   library without internet access; in practice this is almost never the case, and
   the time spent downloading + storing the package sources outweighed any
   potential reproducibility benefit.

2. Packrat tried to maintain the distinction between so-called 'stale' packages;
   those being R packages which were installed by Packrat but are not recorded
   in the lockfile for some reason. This distinction was (1) overall not useful,
   and (2) confusing. `renv` no longer makes this distinction:
   `snapshot()` saves the state of your project library to `renv.lock`, and
   `restore()` loads the state of your project library from `renv.lock`, and
   that's all.

3. In `renv`, the global package cache is enabled by default. This should
   reduce overall disk-space usage as packages can effectively be shared
   across each project using `renv`.

