
# Auto-generated by 'tools/tools-generate-config.R'

config <- list(

  auto.snapshot = function(...) {
    renv_config_get(
      name    = "auto.snapshot",
      type    = "logical[1]",
      default = FALSE,
      args    = list(...)
    )
  },

  bitbucket.host = function(...) {
    renv_config_get(
      name    = "bitbucket.host",
      type    = "character[1]",
      default = "api.bitbucket.org/2.0",
      args    = list(...)
    )
  },

  copy.method = function(...) {
    renv_config_get(
      name    = "copy.method",
      type    = "*",
      default = "auto",
      args    = list(...)
    )
  },

  connect.timeout = function(...) {
    renv_config_get(
      name    = "connect.timeout",
      type    = "integer[1]",
      default = 20L,
      args    = list(...)
    )
  },

  connect.retry = function(...) {
    renv_config_get(
      name    = "connect.retry",
      type    = "integer[1]",
      default = 3L,
      args    = list(...)
    )
  },

  dependency.errors = function(...) {
    renv_config_get(
      name    = "dependency.errors",
      type    = "character[1]",
      default = "reported",
      args    = list(...)
    )
  },

  external.libraries = function(...) {
    renv_config_get(
      name    = "external.libraries",
      type    = "character[*]",
      default = NULL,
      args    = list(...)
    )
  },

  filebacked.cache = function(...) {
    renv_config_get(
      name    = "filebacked.cache",
      type    = "logical[1]",
      default = TRUE,
      args    = list(...)
    )
  },

  github.host = function(...) {
    renv_config_get(
      name    = "github.host",
      type    = "character[1]",
      default = "api.github.com",
      args    = list(...)
    )
  },

  gitlab.host = function(...) {
    renv_config_get(
      name    = "gitlab.host",
      type    = "character[1]",
      default = "gitlab.com",
      args    = list(...)
    )
  },

  hydrate.libpaths = function(...) {
    renv_config_get(
      name    = "hydrate.libpaths",
      type    = "character[*]",
      default = NULL,
      args    = list(...)
    )
  },

  install.staged = function(...) {
    renv_config_get(
      name    = "install.staged",
      type    = "logical[1]",
      default = TRUE,
      args    = list(...)
    )
  },

  mran.enabled = function(...) {
    renv_config_get(
      name    = "mran.enabled",
      type    = "logical[1]",
      default = TRUE,
      args    = list(...)
    )
  },

  repos.override = function(...) {
    renv_config_get(
      name    = "repos.override",
      type    = "character[*]",
      default = NULL,
      args    = list(...)
    )
  },

  rspm.enabled = function(...) {
    renv_config_get(
      name    = "rspm.enabled",
      type    = "logical[1]",
      default = TRUE,
      args    = list(...)
    )
  },

  sandbox.enabled = function(...) {
    renv_config_get(
      name    = "sandbox.enabled",
      type    = "logical[1]",
      default = TRUE,
      args    = list(...)
    )
  },

  shims.enabled = function(...) {
    renv_config_get(
      name    = "shims.enabled",
      type    = "logical[1]",
      default = TRUE,
      args    = list(...)
    )
  },

  snapshot.validate = function(...) {
    renv_config_get(
      name    = "snapshot.validate",
      type    = "logical[1]",
      default = TRUE,
      args    = list(...)
    )
  },

  synchronized.check = function(...) {
    renv_config_get(
      name    = "synchronized.check",
      type    = "logical[1]",
      default = TRUE,
      args    = list(...)
    )
  },

  updates.check = function(...) {
    renv_config_get(
      name    = "updates.check",
      type    = "logical[1]",
      default = FALSE,
      args    = list(...)
    )
  },

  updates.parallel = function(...) {
    renv_config_get(
      name    = "updates.parallel",
      type    = "*",
      default = 2L,
      args    = list(...)
    )
  },

  user.library = function(...) {
    renv_config_get(
      name    = "user.library",
      type    = "logical[1]",
      default = FALSE,
      args    = list(...)
    )
  },

  user.profile = function(...) {
    renv_config_get(
      name    = "user.profile",
      type    = "logical[1]",
      default = FALSE,
      args    = list(...)
    )
  }

)
