
#' Lockfiles
#'
#' A **lockfile** records the state of a project at some point in time. In
#' particular, this implies capturing the \R packages installed (along with
#' their versions) within the project's private library.
#'
#' Projects can be restored from a lockfile using the [restore()] function.
#' This implies re-installing packages into the project's private library,
#' as encoded within the lockfile.
#'
#' While lockfiles are normally generated and used with [snapshot()] /
#' [restore()], they can also hand-edited if so desired. The structure is
#' similar to that of the Windows-style `.ini` file, with some provisioning for
#' nested sections.
#'
#' An example lockfile follows:
#'
#' ```
#' [renv]
#' Version=0.1.0
#'
#' [R]
#' Version=3.5.1
#' Repositories=
#'   CRAN=https://cran.rstudio.com
#'
#' [R/Package/markdown]
#' Package=markdown
#' Version=0.9
#' Source=cran
#' Hash=8515151150d7372bc76e0af15ef5dee0
#'
#' [R/Package/mime]
#' Package=mime
#' Version=0.6
#' Source=cran
#' Hash=b1e49df8aef896bc8c0b749ef1da5a48
#' ```
#'
#' The sections used within a lockfile are described next.
#'
#' @section renv:
#'
#' Information about the version of `renv` used to manage this project.
#'
#' \tabular{ll}{
#' \strong{Version}     \tab The version of the `renv` package used with this project. \cr
#' }
#'
#' @section R:
#'
#' Properties related to the version of \R associated with this project.
#'
#' \tabular{ll}{
#' \strong{Version}      \tab The version of \R used. \cr
#' \strong{Repositories} \tab The \R repositories used in this project. \cr
#' }
#'
#' @section R/Packages:
#'
#' Package records, related to the version of an \R package that was installed
#' at the time the lockfile was generated.
#'
#' \tabular{ll}{
#' \strong{Package}      \tab The package name. \cr
#' \strong{Version}      \tab The package version. \cr
#' \strong{Library}      \tab The library this package was installed in. \cr
#' \strong{Source}       \tab The location from which this package was retrieved. \cr
#' \strong{Hash}         \tab (Optional) A unique hash for this package, used for package caching. \cr
#' }
#'
#' @family reproducibility
#' @name lockfile
#' @rdname lockfile
NULL

## TODO: not yet?
## #' @section Python:
## #'
## #' Metadata related to the Python installation bound to this virtual environment.
## #'
## #' \tabular{ll}{
## #' \strong{Path} \tab Either the path to a Python binary, or a Python virtualenv. \cr
## #' }
## #'
## #' @section Python/Requirements:
## #'
## #' The list of Python packages used (as generated by `pip freeze`) at the point
## #' in time when the lockfile was generated.
## #'


renv_lockfile_init <- function() {

  lockfile <- list()
  lockfile$renv <- list(Version = renv_package_version("renv"))
  lockfile$R      <- renv_lockfile_init_r()
  lockfile$Python <- renv_lockfile_init_python()
  lockfile

}

renv_lockfile_init_r <- function() {
  list(
    Version = format(getRversion()),
    Repositories = getOption("repos")
  )
}

renv_lockfile_init_python <- function() {

  python <- renv_python()
  if (is.null(python))
    return(NULL)

  list(Version = renv_python_version(python))

}

renv_lockfile_load <- function(project = NULL) {

  project <- project %||% renv_project()
  path <- file.path(project, "renv.lock")
  if (renv_file_exists(path))
    return(renv_lockfile_read(path))

  renv_diagnose(project)

}

renv_lockfile_sort <- function(lockfile) {

  # ensure C locale for consistent sorting
  locale <- Sys.getlocale("LC_COLLATE")
  Sys.setlocale("LC_COLLATE", locale = "C")
  on.exit(Sys.setlocale("LC_COLLATE", locale = locale), add = TRUE)

  # sort R packages (if any)
  packages <- lockfile$R$Package
  packages <- packages[sort(names(packages))]
  lockfile$R$Package <- packages

  # return post-sort
  lockfile

}
