
#' Manifests
#'
#' A **manifest** records the state of a virtual environment at some point in
#' time. In particular, this implies capturing the \R packages installed (along
#' with their versions) within the library associated with that virtual
#' environment.
#'
#' Virtual environments can be restored from a manifest using the
#' [restore()] function. This implies re-creating the environment, and
#' reinstalling any \R packages used within the libraries for that environment.
#'
#' While manifest files are normally generated and used with [snapshot()] /
#' [restore()], they can also be generated by hand and edited if so desired.
#' The structure is similar to that of the Windows-style `.ini` file, with
#' some provisioning for nested sections.
#'
#' An example manifest file follows:
#'
#' ```
#' [Environment]
#' Environment=renv-994682bcc73
#' Version=0.1.0
#' Local=FALSE
#'
#' [R]
#' Version=3.5.1
#' Library=dev
#' Overlay=FALSE
#' Repositories=
#'   CRAN=https://cran.rstudio.com
#'
#' [R/Package/markdown]
#' Package=markdown
#' Version=0.9
#' Library=dev
#' Source=cran
#' Hash=8515151150d7372bc76e0af15ef5dee0
#'
#' [R/Package/mime]
#' Package=mime
#' Version=0.6
#' Library=dev
#' Source=cran
#' Hash=b1e49df8aef896bc8c0b749ef1da5a48
#' ```
#'
#' The sections used within a manifest are described next.
#'
#' @section Environment:
#'
#' Base properties for the virtual environment.
#'
#' \tabular{ll}{
#' \strong{Environment} \tab The environment name. \cr
#' \strong{Version}     \tab The version of the `renv` package used with this environment. \cr
#' \strong{Local}       \tab Whether this is a local or global virtual environment. \cr
#' }
#'
#' @section R:
#'
#' Properties related to the version of \R associated with this virtual environment.
#'
#' \tabular{ll}{
#' \strong{Version}      \tab The version of \R used. \cr
#' \strong{Library}      \tab The names of the \R libraries used in this virtual environment. \cr
#' \strong{Overlay}      \tab Whether or not the user library is used (overlaid) in this virtual environment. \cr
#' \strong{Repositories} \tab The \R repositories used in this project. \cr
#' }
#'
#' @section R/Packages:
#'
#' Package records, related to the version of an \R package that was installed
#' at the time the manifest was generated.
#'
#' \tabular{ll}{
#' \strong{Package}      \tab The package name. \cr
#' \strong{Version}      \tab The package version. \cr
#' \strong{Library}      \tab The library this package was installed in. \cr
#' \strong{Source}       \tab The location from which this package was retrieved. \cr
#' \strong{Hash}         \tab (Optional) A unique hash for this package, used for package caching. \cr
#' }
#'
#' @section Python:
#'
#' Metadata related to the Python installation bound to this virtual environment.
#'
#' \tabular{ll}{
#' \strong{Path} \tab Either the path to a Python binary, or a Python virtualenv. \cr
#' }
#'
#' @section Python/Requirements:
#'
#' The list of Python packages used (as generated by `pip freeze`) at the point
#' in time when the manifest was generated.
#'
#' @family reproducibility
#' @name manifest
#' @rdname manifest
NULL

renv_manifest_init <- function() {

  manifest <- list()
  manifest$renv <- list(Version = renv_package_version("renv"))
  manifest$R <- list(Version = format(getRversion()), Repositories = getOption("repos"))
  manifest

}

renv_manifest_load <- function(project = NULL) {

  project <- project %||% renv_state$project()
  path <- file.path(project, "renv.lock")
  if (renv_file_exists(path))
    return(renv_manifest_read(path))

  renv_diagnose(project)

}

