
#' Plan package installations
#'
#' `renv::plan()` resolves the packages required by a project and generates
#' a lockfile, without installing any packages. This allows you to see what
#' `renv::restore()` would do before actually performing the installation.
#'
#' Because packages are not installed, the generated lockfile is based on
#' package metadata from the configured repositories (i.e. the `PACKAGES`
#' file). This means the lockfile may contain only a subset of the fields
#' that would be present in a lockfile generated by [renv::snapshot()],
#' which reads the full `DESCRIPTION` from installed packages. The
#' generated lockfile is still suitable for use with [renv::restore()].
#'
#' @inheritParams renv-params
#'
#' @param packages The packages to be included in the plan. When `NULL`
#'   (the default), all packages currently used in the project will be
#'   included, as determined by [renv::dependencies()].
#'
#' @param dependencies The dependency types to include when resolving
#'   the recursive dependency tree. Defaults to `"strong"` (i.e.
#'   `Depends`, `Imports`, and `LinkingTo`). Use `"most"` to also
#'   include `Suggests`, or `"all"` to include `Enhances` as well.
#'   A character vector of DESCRIPTION field names is also accepted.
#'   See [tools::package_dependencies()] for more details.
#'
#' @param lockfile The path where the generated lockfile should be written.
#'   Use `NULL` to skip writing the lockfile.
#'
#' @return The generated lockfile, invisibly.
#'
#' @examples
#' \dontrun{
#'
#' # plan the packages required by the current project
#' renv::plan()
#'
#' # plan a specific set of packages
#' renv::plan(packages = c("dplyr", "ggplot2"))
#'
#' }
#' @export
plan <- function(packages     = NULL,
                 ...,
                 dependencies = "strong",
                 lockfile     = paths$lockfile(project = project),
                 project      = NULL)
{
  renv_consent_check()
  renv_scope_error_handler()
  renv_dots_check(...)

  project <- renv_project_resolve(project)
  renv_project_lock(project = project)

  # resolve the set of packages to plan for
  packages <- packages %||% renv_plan_packages(project)

  # expand dependency fields
  fields <- renv_dependencies_fields(dependencies)

  # get available packages database
  dbs <- available_packages(type = "source")
  if (is.null(dbs))
    stop("no package repositories are available")

  db <- renv_available_packages_flatten(dbs)

  # resolve the full recursive dependency tree
  packages <- renv_checkout_resolve(packages, db, fields, project = project)

  # build enriched lockfile records from available packages metadata
  records <- renv_checkout_records(packages, db)

  # assemble the lockfile
  new <- renv_lockfile_init(project)
  new$Packages <- records
  new <- renv_lockfile_fini(new, project)
  class(new) <- "renv_lockfile"

  # compare against existing lockfile if one exists
  renv_plan_report(new, project)

  # write the lockfile
  if (!is.null(lockfile)) {
    ensure_parent_directory(lockfile)
    renv_lockfile_write(new, file = lockfile)
  }

  invisible(new)

}

renv_plan_packages <- function(project) {
  renv_dependencies_impl(
    project,
    field = "Package",
    dev = TRUE
  )
}

renv_plan_report <- function(new, project) {

  # read the existing lockfile, if any
  lockpath <- paths$lockfile(project = project)
  old <- if (file.exists(lockpath))
    catch(renv_lockfile_read(lockpath))

  if (inherits(old, "error"))
    old <- NULL

  # compute the diff
  if (is.null(old)) {
    records <- renv_lockfile_records(new)
    if (length(records)) {
      renv_pretty_print_records(
        "The following package(s) will be installed:",
        records
      )
    } else {
      writef("- No packages found for this project.")
    }
    return(invisible())
  }

  actions <- renv_lockfile_diff_packages(old, new)
  if (empty(actions)) {
    writef("- The lockfile is already up to date.")
    renv_condition_signal("renv.plan.up_to_date")
    return(invisible())
  }

  lhs <- renv_lockfile_records(old)
  rhs <- renv_lockfile_records(new)
  renv_pretty_print_records_pair(
    "The following package(s) will be updated in the lockfile:",
    lhs[names(lhs) %in% names(actions)],
    rhs[names(rhs) %in% names(actions)]
  )

}
