

#' @param renv The name of an `renv` environment.
#' @param config The `renv` configuration. See [renv_config()] for more details.
#' @param project The project directory. If an `renv` is already active, the
#'   active project is used; otherwise, the current working directory is used.
#' @param local Boolean; is this a project-local virtual environment?
#'
#' @name renv-params
NULL

#' Create an R Virtual Environment
#'
#' Create a new \R virtual environment, associated with a configuration as
#' generated by [renv_config()].
#'
#' @inheritParams renv-params
#'
#' @family renv
#'
#' @export
renv_create <- function(renv, config = renv_config(), local = NULL) {

  local <- renv_local(local)
  path <- ensure_no_renv(renv, local = local)
  ensure_directory(dirname(path))
  renv_bootstrap(local = local)
  renv_config_write(config, path)

  if (renv_verbose()) {
    fmt <- "* Created %s environment '%s'."
    messagef(fmt, if (local) "local virtual" else "virtual", renv)
  }

  invisible(renv)
}


#' Activate an R Virtual Environment
#'
#' Activate an \R virtual environment. This binds the requested project to the
#' virtual environment called `name`. Newly-launched \R sessions in this project
#' will use this virtual environment.
#'
#' @inheritParams renv-params
#'
#' @family renv
#'
#' @export
renv_activate <- function(renv, project = NULL, local = NULL) {
  project <- renv_active_project(project)

  local <- renv_local(local)
  ensure_existing_renv(renv, local)

  renv_write_infrastructure(project, renv, local)

  if (renv_verbose()) {
    fmt <- "* Activating R virtual environment '%s' ..."
    messagef(fmt, renv)
  }

  reason <- sprintf("renv '%s' activated", renv)
  renv_request_restart(reason)
}

#' Deactivate an R Virtual Environment
#'
#' Deactivate the active virtual environment.
#'
#' @inheritParams renv-params
#'
#' @family renv
#'
#' @export
renv_deactivate <- function(project = NULL) {
  project <- renv_active_project(project)

  active <- file.path(project, "renv/active")
  if (file.exists(active)) {
    dcf <- read.dcf(active, all = TRUE)
    if (renv_verbose()) {
      fmt <- "* Deactivating renv '%s' ..."
      messagef(fmt, dcf$name)
    }
  }

  renv_remove_infrastructure()
  renv_request_restart("renv deactivated")
}

#' Load an R Virtual Environment.
#'
#' Load the \R virtual environment called `renv`.
#'
#' Normally, this is done automatically on session startup by the infrastructure
#' initialized by [renv_activate()] -- users should not need to call this
#' function directly.
#'
#' @inheritParams renv-params
#'
#' @export
renv_load <- function(renv = NULL, project = NULL, local = NULL) {
  project <- renv_active_project(project)

  # when 'renv' is not specified, use the active virtual environment associated
  # with the project (if any)
  if (is.null(renv)) {
    active <- file.path(project, "renv/active")
    if (file.exists(active)) {
      dcf <- read.dcf(active, all = TRUE)
      renv <- dcf$name
      local <- as.logical(dcf$local)
    }
  }

  local <- renv_local(local)
  path <- ensure_existing_renv(renv, local = local)
  config <- renv_config_read(path)

  renv_set_active_project(project)
  renv_set_active_renv(renv)

  renv_load_r_version(config)
  renv_load_repos(config)
  renv_load_libpaths(config, local)

  # report environment changes to the user
  if (renv_verbose()) {

    fmt <- if (local)
      "* Local virtual environment '%s' loaded."
    else
      "* Virtual environment '%s' loaded."

    messagef(fmt, basename(renv))
    message()

    paths <- paste("-", shQuote(.libPaths()), collapse = "\n")
    message("* Using library paths:")
    message(paths)

  }

  invisible(renv)
}

#' Edit an R Virtual Environment
#'
#' Edit the configuration file associated with an \R virtual environment. This
#' can be useful if you need to manually tweak or edit values in a pre-existing
#' environment.
#'
#' @inheritParams renv-params
#'
#' @family renv
#'
#' @export
renv_edit <- function(renv = NULL, local = NULL) {
  renv <- renv_active_renv(renv)
  local <- renv_local(local)
  path <- ensure_existing_renv(renv, local)
  file.edit(path)
}

