

#' @param renv The name of an `renv` environment.
#' @param config The `renv` configuration. See [renv_config()] for more details.
#' @param project The project directory. If an `renv` is already active, the
#'   active project is used; otherwise, the current working directory is used.
#'
#' @name renv-params
NULL

#' Create an R Virtual Environment
#'
#' Create a new \R virtual environment, associated with a configuration as
#' generated by [renv_config()].
#'
#' @inheritParams renv-params
#'
#' @family renv
#'
#' @export
renv_create <- function(renv, config = renv_config()) {

  path <- ensure_no_renv(renv)
  ensure_directory(dirname(path))
  renv_bootstrap()
  renv_config_write(config, path)

  if (renv_verbose()) {
    fmt <- "* Created renv at path '%s'."
    messagef(fmt, aliased_path(path))
  }

  invisible(renv)
}


#' Activate an R Virtual Environment
#'
#' Activate an \R virtual environment. This binds the requested project to the
#' virtual environment called `name`. Newly-launched \R sessions in this project
#' will use this virtual environment.
#'
#' @inheritParams renv-params
#'
#' @family renv
#'
#' @export
renv_activate <- function(renv, project = NULL) {
  project <- renv_active_project(project)
  ensure_existing_renv(renv)

  renv_write_infrastructure(project, renv)

  if (renv_verbose()) {
    fmt <- "* Activating renv '%s' ..."
    messagef(fmt, renv)
  }

  reason <- sprintf("renv '%s' activated", renv)
  renv_request_restart(reason)
}

#' Deactivate an R Virtual Environment
#'
#' Deactivate the active virtual environment.
#'
#' @inheritParams renv-params
#'
#' @family renv
#'
#' @export
renv_deactivate <- function(project = NULL) {
  project <- renv_active_project(project)

  active <- renv_paths_local("active")
  if (file.exists(active)) {
    name <- readLines(active, warn = FALSE)
    if (renv_verbose()) {
      fmt <- "* Deactivating renv '%s' ..."
      messagef(fmt, name)
    }
  }

  renv_remove_infrastructure()
  renv_request_restart("renv deactivated")
}

#' Load an R Virtual Environment.
#'
#' Load the \R virtual environment called `renv`.
#'
#' Normally, this is done automatically on session startup by the infrastructure
#' initialized by [renv_activate()] -- users should not need to call this
#' function directly.
#'
#' @inheritParams renv-params
#'
#' @export
renv_load <- function(renv, project = NULL) {
  project <- renv_active_project(project)

  path <- ensure_existing_renv(renv)
  config <- renv_config_read(path)

  renv_set_active_project(project)

  # check R version (note that it is the responsibility of the user,
  # or the front-end, to ensure that R versions match)
  version <- config$r_version
  if (!is_compatible_version(version, getRversion())) {
    fmt <- "renv '%s' requested R version '%s' but '%s' is currently being used"
    warningf(fmt, renv, version, getRversion())
  }

  # prepare the library paths
  renv <- file.path(renv_paths_renv(), sprintf("renv-%s", config$renv_version))
  libs <- rev(renv_paths_lib(config$r_libs))
  lapply(libs, ensure_directory)

  libpaths <- c(libs, renv, if (config$r_libs_overlay) .libPaths())
  .libPaths(libpaths)

  # report environment changes to the user
  if (renv_verbose()) {

    fmt <- "* renv '%s' loaded. Using library paths:"
    messagef(fmt, renv)

    paths <- paste("-", shQuote(.libPaths()), collapse = "\n")
    message(paths)

  }

  invisible(renv)
}

#' Edit an R Virtual Environment
#'
#' Edit the configuration file associated with an \R virtual environment. This
#' can be useful if you need to manually tweak or edit values in a pre-existing
#' environment.
#'
#' @inheritParams renv-params
#'
#' @family renv
#'
#' @export
renv_edit <- function(renv = NULL) {
  renv <- renv_active_renv(renv)
  path <- ensure_existing_renv(renv)
  file.edit(path)
}

