
#' Use a set of Packages
#'
#' Given a set of \R package requirements, install those packages into the
#' library path requested via `library`, and then activate that library path.
#'
#' Normally, the call to `renv::use()` is generated by [embed()]. This gives
#' a mechanism for users to encode an `renv` lockfile directly into an \R
#' script, such that running that script will then use the packages requested
#' via the generated `renv::use()` call.
#'
#' @param ...
#'   The \R packages to be used with this script.
#'
#' @param library
#'   The library path into which the requested packages should be installed.
#'
#' @return This function is normally called for its side effects.
use <- function(..., library = NULL) {

  # allow caching in this context
  renv_scope_options(renv.cache.linkable = TRUE)

  # prepare library and activate library
  library <- library %||% renv_use_libpath()
  ensure_directory(library)
  renv_libpaths_set(c(library, .libPaths()))

  # install packages
  install(..., library = library, prompt = FALSE)

}

renv_use_libpath <- function() {
  renv_global("use.library", tempfile("renv-library-"))
}
